# Generated by Django 5.1.1 on 2024-10-08 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certification_process", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="about",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="criterion",
            name="about",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="criterion",
            name="benefit",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="criterion",
            name="credits",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="criterion",
            name="functional_requirements_tier_1",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="criterion",
            name="functional_requirements_tier_2",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="criterion",
            name="functional_requirements_tier_3",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="criterion",
            name="prefix",
            field=models.CharField(default="--", max_length=10),
        ),
        migrations.AddField(
            model_name="criterion",
            name="problem_statement",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="criterion",
            name="purpose",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="criterion",
            name="required_proof",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="criterion",
            name="section",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="criteria",
                to="certification_process.section",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="criterion",
            name="tenant_enablement_requirements_tier_1",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="criterion",
            name="tenant_enablement_requirements_tier_2",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="criterion",
            name="tenant_enablement_requirements_tier_3",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="criterion",
            name="user_story",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="section",
            name="about",
            field=models.TextField(blank=True),
        ),
    ]
