# Generated by Django 5.1.1 on 2024-10-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "certification_process",
            "0002_category_about_criterion_about_criterion_benefit_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="criterion",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
