# Generated by Django 5.1.1 on 2024-10-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certification_process", "0004_project_remove_criterion_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="criterion",
            name="credit_allocation",
            field=models.TextField(blank=True),
        ),
    ]
